package com.atlasmc.desertdweller.cooking.effects;

public enum CustomEffectType {
	EXPGAINOVERTIME,
	MELEEDAMAGEBOOST,
	TRIDENTDAMAGEBOOST,
	SWORDDAMAGEBOOST,
	BATTLEAXEDAMAGEBOOST,
	SICKLEDAMAGEBOOST,
	BOWDAMAGEBOOST,
	OFFENSIVEMAGICBOOST,
	DEFENSIVEMAGICBOOST,
	PASSIVEREGEN,
	DEBUFFREMOVAL,
	TARGETBUFFREMOVAL,
	ANTISEEKING,
	CROSSBOWDAMAGEBOOST
}
